"""Status constants for TradingLab Data Engine."""

DATASET_LIFECYCLE_STATUS_RAW = "RAW"
DATASET_LIFECYCLE_STATUS_VALIDATED = "VALIDATED"
DATASET_LIFECYCLE_STATUS_ACCEPTED = "ACCEPTED"
DATASET_LIFECYCLE_STATUS_QUARANTINED = "QUARANTINED"
DATASET_LIFECYCLE_STATUS_REJECTED = "REJECTED"
DATASET_LIFECYCLE_STATUS_DEPRECATED = "DEPRECATED"

VALIDATION_STATUS_NOT_VALIDATED = "not_validated"
VALIDATION_STATUS_VALID = "valid"
VALIDATION_STATUS_VALID_WITH_WARNINGS = "valid_with_warnings"
VALIDATION_STATUS_INVALID = "invalid"

DATASET_LIFECYCLE_STATUSES = (
    DATASET_LIFECYCLE_STATUS_RAW,
    DATASET_LIFECYCLE_STATUS_VALIDATED,
    DATASET_LIFECYCLE_STATUS_ACCEPTED,
    DATASET_LIFECYCLE_STATUS_QUARANTINED,
    DATASET_LIFECYCLE_STATUS_REJECTED,
    DATASET_LIFECYCLE_STATUS_DEPRECATED,
)

VALIDATION_STATUSES = (
    VALIDATION_STATUS_NOT_VALIDATED,
    VALIDATION_STATUS_VALID,
    VALIDATION_STATUS_VALID_WITH_WARNINGS,
    VALIDATION_STATUS_INVALID,
)

__all__ = [
    "DATASET_LIFECYCLE_STATUS_ACCEPTED",
    "DATASET_LIFECYCLE_STATUS_DEPRECATED",
    "DATASET_LIFECYCLE_STATUS_QUARANTINED",
    "DATASET_LIFECYCLE_STATUS_RAW",
    "DATASET_LIFECYCLE_STATUS_REJECTED",
    "DATASET_LIFECYCLE_STATUS_VALIDATED",
    "DATASET_LIFECYCLE_STATUSES",
    "VALIDATION_STATUS_INVALID",
    "VALIDATION_STATUS_NOT_VALIDATED",
    "VALIDATION_STATUS_VALID",
    "VALIDATION_STATUS_VALID_WITH_WARNINGS",
    "VALIDATION_STATUSES",
]
